-- ============================================================================
-- Sprint 4 — Seed idempotente do catálogo de Estratégias (Seção 6.4 do plano)
-- 15 padrões comprovados de tráfego pago para e-commerce, versão 1.
-- Idempotente via `on conflict (slug)`: rodar de novo apenas atualiza o
-- conteúdo (permite editar o catálogo reaplicando esta migration manualmente).
-- ============================================================================

insert into public.estrategias
  (slug, titulo, categoria, canal, objetivo, quando_usar, impacto, pre_requisitos, passos, guardrails, kpi_sucesso, nivel, versao)
values
  (
    'full-funnel-estrutura',
    'Estrutura full-funnel (topo/meio/fundo)',
    'Estrutura de conta',
    'ambos',
    'Escalar com eficiência separando o funil por intenção',
    'Conta roda tudo junto, sem separação por intenção do público',
    array['cac_down','roas_up']::impacto_estrategia[],
    '["Pixel/tag instalado e disparando eventos de conversão","Pelo menos 30 conversões no último mês"]'::jsonb,
    '["Mapear o funil da loja: topo (descoberta), meio (consideração), fundo (decisão)","Criar campanha de topo com público amplo/interesses para gerar tráfego qualificado","Criar campanha de meio com retargeting de quem engajou ou visitou sem comprar","Criar campanha de fundo com retargeting de carrinho abandonado e visualização de produto","Definir budget inicial: 50% fundo, 30% meio, 20% topo","Acompanhar o CPA por camada nas primeiras 2 semanas antes de redistribuir budget"]'::jsonb,
    '["Nunca zerar o topo — sem ele o funil seca em 2 a 3 semanas","O CPA do fundo não deve superar o CPA-alvo do cliente","Revisar a divisão de budget semanalmente, não diariamente (ruído estatístico)"]'::jsonb,
    'CAC médio da conta cai e o ROAS do fundo se mantém igual ou acima da meta em 30 dias',
    'iniciante',
    1
  ),
  (
    'meta-advantage-shopping',
    'Advantage+ Shopping (ASC)',
    'Automação de aquisição',
    'meta',
    'Aquisição e-commerce com otimização automática do Meta',
    'Catálogo do Meta pronto e a conta já gera 50 ou mais conversões por semana',
    array['roas_up']::impacto_estrategia[],
    '["Catálogo de produtos conectado e aprovado no Commerce Manager","Pixel com eventos Purchase configurados","Histórico de pelo menos 50 conversões nos últimos 7 dias"]'::jsonb,
    '["Criar campanha Advantage+ Shopping selecionando o catálogo completo","Deixar o público 100% automático, sem segmentação manual","Configurar o orçamento no nível da campanha (CBO nativo do ASC)","Subir de 3 a 5 criativos variados para o algoritmo testar","Aguardar de 4 a 7 dias de aprendizado sem alterar budget ou criativos","Escalar o orçamento em incrementos de até 20% a cada 2 ou 3 dias"]'::jsonb,
    '["Não pausar e reativar a campanha — reseta o aprendizado","Não editar a segmentação manualmente — contraria o propósito do ASC","Escalar aos poucos: saltos de budget acima de 20% derrubam a performance"]'::jsonb,
    'ROAS do ASC igual ou superior à média das campanhas manuais de vendas em 14 dias',
    'iniciante',
    1
  ),
  (
    'google-pmax-feed',
    'Performance Max com feed otimizado',
    'Automação de aquisição',
    'google',
    'Aquisição cross-rede (Search, Display, YouTube, Shopping) via feed',
    'Feed do Merchant Center saudável, sem reprovações, e quer ampliar alcance',
    array['roas_up']::impacto_estrategia[],
    '["Conta no Google Merchant Center vinculada e sem produtos reprovados","Feed de produtos com título, imagem e preço atualizados","Conversões de compra rastreadas via Google Ads ou GA4"]'::jsonb,
    '["Auditar o feed: títulos descritivos, imagens de qualidade, preços sincronizados","Criar campanha Performance Max com o feed completo","Adicionar assets de texto e imagem para os formatos que não são Shopping","Definir meta de CPA ou ROAS alinhada ao histórico da conta","Excluir marcas e termos irrelevantes via lista de exclusão de marca","Revisar o relatório de segmentos de insights semanalmente"]'::jsonb,
    '["Feed com produtos reprovados derruba o alcance — corrigir antes de escalar","Não definir meta de ROAS agressiva demais no início — trava o aprendizado","Monitorar o relatório de canal: se Display ou YouTube consumir budget sem converter, ajustar a meta"]'::jsonb,
    'ROAS igual ou superior ao Shopping tradicional, com alcance 20% ou mais maior em 30 dias',
    'avancado',
    1
  ),
  (
    'meta-retargeting-dpa',
    'Retargeting dinâmico de catálogo (DPA)',
    'Recuperação',
    'meta',
    'Recuperar carrinho abandonado e visitantes de produto',
    'Pixel e catálogo ativos, com tráfego de visitantes de produto',
    array['cac_down']::impacto_estrategia[],
    '["Pixel disparando ViewContent, AddToCart e Purchase","Catálogo de produtos sincronizado"]'::jsonb,
    '["Criar conjunto de anúncios dinâmicos usando o catálogo completo","Segmentar por janela de 7 dias (visitou produto) e 3 dias (carrinho abandonado)","Usar o formato carrossel com os produtos vistos automaticamente","Definir budget modesto — de 10% a 15% do total — é público quente e converte com pouco gasto","Testar oferta de incentivo (frete grátis, cupom) para carrinho abandonado há 3 dias ou mais"]'::jsonb,
    '["Excluir quem já comprou o produto nos últimos 7 dias","Não usar desconto agressivo sem necessidade — corrói margem","Limitar a frequência para não cansar o público (no máximo cerca de 3 vezes por semana por pessoa)"]'::jsonb,
    'CPA do retargeting pelo menos 30% menor que o CPA médio de aquisição fria',
    'iniciante',
    1
  ),
  (
    'meta-publico-amplo-criativo',
    'Público amplo + criativo-led',
    'Escala',
    'meta',
    'Escalar com o algoritmo decidindo o público, apostando no criativo',
    'Boa esteira de criativos e Pixel maduro, com 100 ou mais conversões',
    array['roas_up']::impacto_estrategia[],
    '["Pixel com 100 ou mais conversões nos últimos 30 dias","Pelo menos 4 criativos ativos e testados"]'::jsonb,
    '["Criar conjunto com público amplo, sem interesses, só localização e idade","Deixar a otimização em conversão (compra)","Subir de 4 a 6 criativos com ângulos diferentes: dor, prova social, oferta, UGC","Dar de 3 a 5 dias de aprendizado sem mexer","Cortar os criativos com CPA acima da meta e manter os vencedores","Renovar a esteira de criativos a cada 2 ou 3 semanas para evitar fadiga"]'::jsonb,
    '["Não adicionar segmentação de interesse — contraria a lógica do público amplo","Não julgar criativo em menos de 3 dias ou 1000 impressões","Se a fadiga aparecer (CTR caindo, CPA subindo), trocar o criativo antes de aumentar o budget"]'::jsonb,
    'ROAS mantido ou superior ao das campanhas segmentadas, com CAC estável em escala',
    'avancado',
    1
  ),
  (
    'meta-lookalike-compradores',
    'Lookalike baseado em valor (compradores)',
    'Aquisição qualificada',
    'meta',
    'Encontrar novos clientes parecidos com os melhores compradores',
    'Base de 100 ou mais compradores identificados no Pixel ou CRM',
    array['cac_down']::impacto_estrategia[],
    '["Pelo menos 100 compradores na base (Pixel ou upload de lista)","Valor de compra disponível para priorizar clientes de maior ticket"]'::jsonb,
    '["Criar público personalizado de compradores dos últimos 180 dias","Gerar lookalike de 1% a 3% com base nesse público, priorizando por valor quando disponível","Criar campanha de aquisição usando o lookalike como público principal","Excluir compradores atuais do público de veiculação","Atualizar a base de origem do lookalike a cada 30 a 60 dias"]'::jsonb,
    '["Lookalike com menos de 100 pessoas na base de origem tende a ficar instável","Não sobrepor múltiplos lookalikes (1%, 2%, 3%) na mesma campanha — gera canibalização","Revisar a base de origem periodicamente — cliente antigo demais distorce o padrão"]'::jsonb,
    'CAC do lookalike menor que o CAC médio de públicos de interesse em 30 dias',
    'iniciante',
    1
  ),
  (
    'exclusao-compradores-recentes',
    'Exclusão de compradores recentes',
    'Higiene de conta',
    'ambos',
    'Cortar desperdício de verba anunciando para quem já comprou',
    'Sempre — é higiene básica de qualquer conta madura',
    array['cac_down']::impacto_estrategia[],
    '["Pixel ou tag de conversão disparando corretamente"]'::jsonb,
    '["Criar público de compradores dos últimos 30 a 60 dias, ajustando pela recompra do nicho","Adicionar esse público como exclusão em todas as campanhas de aquisição","Manter uma campanha separada de recompra ou upsell para esse público excluído","Revisar a janela de exclusão a cada trimestre conforme o ciclo de recompra real"]'::jsonb,
    '["Não excluir de campanhas de recompra ou pós-venda — o objetivo ali é justamente esse público","Ajustar a janela pelo ciclo do produto: consumível recorrente precisa de janela mais curta"]'::jsonb,
    'Redução mensurável de gasto desperdiçado em impressões para quem já comprou',
    'iniciante',
    1
  ),
  (
    'teste-criativo-framework',
    'Framework de teste de criativo (ângulos e hooks)',
    'Criativo',
    'ambos',
    'Achar o criativo vencedor de forma sistemática',
    'Sempre — processo contínuo, não pontual',
    array['roas_up']::impacto_estrategia[],
    '["Pelo menos 3 ângulos de mensagem diferentes para testar: dor, desejo, prova social"]'::jsonb,
    '["Definir de 3 a 4 ângulos de mensagem (hook) por rodada de teste","Produzir de 1 a 2 variações de formato por ângulo: vídeo curto, estático, carrossel","Rodar todos os candidatos com budget igual em um conjunto de teste isolado","Definir o critério de corte antes de começar, por exemplo CPA acima de X ou CTR abaixo de Y após 1000 impressões","Promover o(s) vencedor(es) para a campanha principal e arquivar o resto","Repetir o ciclo a cada 2 ou 3 semanas"]'::jsonb,
    '["Testar com budget igual entre variações — senão o teste fica viesado","Não julgar antes do volume mínimo de impressões definido","Documentar o que venceu e por quê — constrói repertório para o cliente ao longo do tempo"]'::jsonb,
    'Pelo menos 1 criativo vencedor por rodada, com CPA abaixo da meta',
    'avancado',
    1
  ),
  (
    'meta-capi-server-side',
    'Server-side tracking (CAPI)',
    'Mensuração',
    'meta',
    'Recuperar atribuição perdida com bloqueadores e iOS',
    'Mensuração fraca pós-iOS 14, com eventos de Pixel divergindo do real',
    array['roas_up']::impacto_estrategia[],
    '["Acesso a servidor/backend do e-commerce ou uso de parceiro (Shopify, GTM Server-side)","Eventos de conversão mapeados: Purchase, AddToCart, entre outros"]'::jsonb,
    '["Configurar a Conversions API via parceiro nativo (Shopify/VTEX) ou GTM Server-side","Espelhar os mesmos eventos do Pixel no servidor, com deduplicação por event_id","Validar no Events Manager que os eventos batem — Pixel e servidor, sem duplicar contagem","Habilitar parâmetros avançados de correspondência com email e telefone com hash","Monitorar a taxa de correspondência de eventos (Event Match Quality) e ajustar"]'::jsonb,
    '["Sem deduplicação correta, o mesmo evento conta 2 vezes e distorce a otimização","Nunca enviar dado pessoal sem hash SHA-256 — obrigatório e é requisito de LGPD","Validar em ambiente de teste antes de ativar em produção"]'::jsonb,
    'Taxa de correspondência de eventos (EMQ) sobe e a atribuição de conversões se aproxima do real',
    'avancado',
    1
  ),
  (
    'google-defesa-marca-search',
    'Defesa de marca + termos não-marca (Search)',
    'Busca',
    'google',
    'Proteger a demanda de marca e capturar quem já busca a categoria',
    'Marca com volume de busca próprio: nome da loja, produto exclusivo',
    array['cac_down']::impacto_estrategia[],
    '["Conta no Google Ads com conversão de compra rastreada","Volume de busca de marca identificável no Google Ads ou Search Console"]'::jsonb,
    '["Criar campanha de Search exclusiva para termos de marca: nome da loja e variações","Definir lances de marca com CPA baixo — é tráfego barato e de alta intenção","Criar campanha separada para termos não-marca da categoria (genéricos)","Usar palavras-chave negativas para não misturar orçamento entre marca e não-marca","Monitorar concorrentes comprando o nome da marca e ajustar o lance de defesa se necessário"]'::jsonb,
    '["Nunca misturar marca e não-marca na mesma campanha — mascara o CPA real de cada uma","Não abandonar a campanha de marca achando que é tráfego orgânico garantido — o concorrente pode comprar o termo"]'::jsonb,
    'CAC de marca se mantém baixo e a captura de não-marca cresce sem inflar o CAC médio',
    'iniciante',
    1
  ),
  (
    'meta-cbo-orcamento-campanha',
    'CBO / orçamento no nível de campanha',
    'Estrutura de conta',
    'meta',
    'Deixar o algoritmo alocar orçamento entre conjuntos automaticamente',
    'Três ou mais conjuntos comparáveis, com mesmo objetivo e públicos parecidos',
    array['roas_up']::impacto_estrategia[],
    '["Pelo menos 3 conjuntos de anúncios com objetivo e maturidade parecidos"]'::jsonb,
    '["Ativar o orçamento no nível da campanha (CBO)","Agrupar apenas conjuntos comparáveis, do mesmo funil e objetivo, na mesma campanha","Definir o orçamento total e deixar o algoritmo distribuir entre os conjuntos","Aguardar de 3 a 5 dias antes de avaliar a distribuição","Remover conjuntos que ficam consistentemente sem verba — sinal de baixa relevância"]'::jsonb,
    '["Não colocar conjuntos de funil diferente (topo e fundo) na mesma CBO — o algoritmo tende a favorecer o de conversão mais fácil e o topo seca","Dar tempo de aprendizado antes de julgar a distribuição"]'::jsonb,
    'ROAS da campanha CBO igual ou superior à soma das campanhas ABO equivalentes',
    'iniciante',
    1
  ),
  (
    'regras-escala-disciplina',
    'Regras de escala (subir vencedor / cortar CPA alto)',
    'Otimização contínua',
    'ambos',
    'Disciplina de escala baseada em regra, não em achismo',
    'Contas em crescimento, com histórico suficiente para definir limites',
    array['cac_down','roas_up']::impacto_estrategia[],
    '["Histórico de pelo menos 2 semanas de dados por campanha ou conjunto","Meta de CPA ou ROAS definida com o cliente"]'::jsonb,
    '["Definir a meta de CPA/ROAS e a janela de avaliação, por exemplo os últimos 3 dias","Criar regra automática ou checklist manual: subir o budget de 15% a 20% quando abaixo da meta por 3 dias seguidos","Criar regra de corte: pausar ou reduzir o budget quando o CPA supera a meta por 3 dias seguidos","Registrar toda alteração de budget ou status no histórico da conta","Revisar as regras mensalmente — a meta muda conforme o negócio evolui"]'::jsonb,
    '["Nunca escalar em saltos maiores que 20% de uma vez — quebra a fase de aprendizado","Esperar a janela mínima de avaliação — decisão em cima de 1 dia é ruído","Toda ação de budget ou status entra no audit_log — rastreabilidade é inegociável"]'::jsonb,
    'CAC estável ou em queda com o budget total crescendo',
    'avancado',
    1
  ),
  (
    'message-match-anuncio-landing',
    'Message match anúncio → landing → oferta',
    'Conversão',
    'ambos',
    'Aumentar a taxa de conversão alinhando a promessa do anúncio à página',
    'Landing page genérica, com taxa de conversão abaixo do esperado para o tráfego',
    array['roas_up']::impacto_estrategia[],
    '["Página de destino específica, ou ao menos filtrada, por criativo ou oferta"]'::jsonb,
    '["Mapear a promessa central de cada criativo: oferta, produto ou benefício","Direcionar cada criativo para a página que reforça a MESMA promessa, com o produto certo e a mesma oferta no topo","Repetir a headline ou oferta do anúncio logo acima da dobra na landing","Remover fricção entre o clique e a conversão, com menos passos até o checkout","Testar a página com tráfego real e medir a taxa de conversão por criativo e página"]'::jsonb,
    '["Nunca mandar tráfego pago para a home genérica quando o anúncio promete um produto específico","Página lenta mata a conversão antes de qualquer teste de criativo — checar a velocidade primeiro"]'::jsonb,
    'Taxa de conversão da landing sobe sem aumentar o CPC ou o CPM',
    'iniciante',
    1
  ),
  (
    'loop-pos-compra-retencao',
    'Loop pós-compra (upsell + retargeting de retenção)',
    'Retenção',
    'ambos',
    'Aumentar o LTV da base de clientes ativa',
    'Base de clientes ativa com potencial de recompra ou upsell',
    array['faturamento_up']::impacto_estrategia[],
    '["Base de clientes identificável via Pixel, CRM ou lista de e-mail","Catálogo com produtos complementares ou de recompra"]'::jsonb,
    '["Segmentar a base por tempo desde a última compra, por exemplo 30, 60 ou 90 dias","Criar campanha de upsell mostrando produtos complementares ao que já foi comprado","Criar campanha de recompra para quem está no ciclo esperado de recompra do produto","Oferecer um incentivo leve para reativação, como frete grátis ou brinde, na janela de 60 a 90 dias sem comprar","Medir o LTV por coorte de entrada e comparar com e sem o loop ativo"]'::jsonb,
    '["Não usar desconto pesado logo após a primeira compra — corrói margem sem necessidade","Segmentar pelo ciclo real de recompra do produto, não por um número genérico"]'::jsonb,
    'LTV médio da coorte sobe e o faturamento de clientes recorrentes cresce como percentual do total',
    'avancado',
    1
  ),
  (
    'criativo-estilo-ugc',
    'Criativo estilo UGC',
    'Criativo',
    'meta',
    'Aumentar CTR e confiança com estética autêntica',
    'Fadiga de criativo produzido, com CTR em queda',
    array['roas_up']::impacto_estrategia[],
    '["Produto físico disponível para gravação ou parceria com criador"]'::jsonb,
    '["Produzir ou encomendar vídeos curtos em estilo autêntico, não-produzido, mostrando o produto em uso","Testar ganchos (hooks) nos primeiros 3 segundos: problema, curiosidade ou resultado","Usar legendas embutidas e formato vertical nativo de Reels/Stories","Rodar como teste isolado contra o criativo produzido atual","Escalar o formato vencedor e renovar o ângulo a cada poucas semanas"]'::jsonb,
    '["UGC com áudio ou luz ruins derruba a credibilidade — manter um mínimo de qualidade técnica","Seguir as normas de divulgação e publicidade ao usar criador pago"]'::jsonb,
    'CTR do UGC supera o criativo produzido e o CPA se mantém igual ou menor',
    'iniciante',
    1
  )
on conflict (slug) do update set
  titulo         = excluded.titulo,
  categoria      = excluded.categoria,
  canal          = excluded.canal,
  objetivo       = excluded.objetivo,
  quando_usar    = excluded.quando_usar,
  impacto        = excluded.impacto,
  pre_requisitos = excluded.pre_requisitos,
  passos         = excluded.passos,
  guardrails     = excluded.guardrails,
  kpi_sucesso    = excluded.kpi_sucesso,
  nivel          = excluded.nivel,
  versao         = excluded.versao;

-- Histórico de versão (v1) para cada estratégia do catálogo.
insert into public.estrategia_versoes (estrategia_id, versao, mudanca)
select id, 1, 'Versão inicial do catálogo.'
from public.estrategias
on conflict (estrategia_id, versao) do nothing;
